name: foodking_delivery_boy
version: 3.0.1+12
publish_to: none
description: At its core, the NataLee Pro Food Ecosystem is driven by a mission to redefine global food systems. It aims to bridge the gap between cutting-edge food technologies and traditional culinary practices, fostering a harmonious relationship between humans and the planet.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^1.5.0
  animated_bottom_navigation_bar: ^1.1.0
  flutter_screenutil: ^5.9.0
  image_picker: ^1.2.0
  get_storage: ^2.0.3
  flutter_svg: ^2.2.1
  lottie: ^3.3.1
  modal_bottom_sheet: ^3.0.0
  expansion_tile_card: ^3.0.0
  bottom_bar: ^2.0.5
  rflutter_alert: ^2.0.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  connectivity_plus: ^7.0.0
  firebase_messaging: ^15.2.9
  firebase_core: ^3.15.2
  flutter_local_notifications: ^19.4.1
  flutter_launcher_icons: ^0.14.4
  google_maps_flutter: ^2.13.1
  location: ^7.0.1
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  url_launcher: ^6.3.2
  map_launcher: ^4.4.2
  webview_flutter: ^4.13.0
  flutter_html: 3.0.0

  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "ic_launcher"
  ios: true

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
